encoding: utf-8
markdown: redcarpet
pygments: true
permalink: /posts/:title
port: 4000

exclude:
  - Rakefile
  - bin

assets:
  js_compressor: uglifier
  css_compressor: sass
  cache: true

title: Jason Codes
subtitle: "code &amp; rants of Jason Weathered"
url: http://jasoncodes.com
disqus_id: jasoncodes
google_analytics_id: UA-12287090-1
feed_url: http://jasoncodes.com/feed

author:
  name: Jason Weathered
  email: jason@jasoncodes.com

links:

  - key: twitter
    url: https://twitter.com/jasoncodes
    name: Twitter
    suffix: stream
    me: true

  - key: github
    url: https://github.com/jasoncodes
    name: GitHub
    suffix: repositories
    me: true

  - key: stackoverflow
    url: http://stackoverflow.com/users/3736/jason-weathered
    name: Stack Overflow
    suffix: questions &amp; answers
    me: true
