markdown: rdiscount
pygments: true
permalink: /posts/:title
server_port: 3000

exclude:
  - Rakefile
  - bin

title: Jason Codes
url: http://jasoncodes.com

author:
  name: Jason Weathered
  email: jason@jasoncodes.com
