encoding: utf-8
markdown: kramdown
permalink: /posts/:title
port: 4000

exclude:
  - Rakefile
  - bin

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  auto_ids: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      disable: true
    block:
      wrap: false

assets:
  gzip: true
  sources:
    - _assets/stylesheets
    - _assets/javascripts

title: Jason Codes
subtitle: "code &amp; rants of Jason Weathered"
url: https://jasoncodes.com
feed_url: https://jasoncodes.com/feed

author:
  name: Jason Weathered
  email: jason@jasoncodes.com

links:

  - key: mastodon
    url: https://mastodon.social/@jasoncodes
    name: Mastodon
    suffix: toots
    me: true

  - key: github
    url: https://github.com/jasoncodes
    name: GitHub
    suffix: repositories
    me: true

  - key: stackoverflow
    url: https://stackoverflow.com/users/3736/jason-weathered
    name: Stack Overflow
    suffix: questions &amp; answers
    me: true
